{$DEFINE PEAKTOP:IDE/ERP/MAINMENU_OBJNAMES.INC}
const //=================== PEAKTOP:IDE/ERP/MAINMENU_OBJNAMES.INC ==============
  obj_name_erpide_mimainbase      = 'miMainBase';
  obj_name_erpide_actbasenew      = 'actBaseNew';
  obj_name_erpide_actbaseopen     = 'actBaseOpen';
  obj_name_erpide_actbaseclose    = 'actBaseClose';
  obj_name_erpide_actbaseatchs    = 'actBaseAtchs';
  obj_name_erpide_actbasefs       = 'actBaseFileSystem';
  obj_name_erpide_actbaseconfig   = 'actBaseConfigurator';
  obj_name_erpide_actbasemenu     = 'actBaseMenu';
  obj_name_erpide_actbasebuffer   = 'actBaseBuffer';
  obj_name_erpide_actbaserecent   = 'actBaseRecent';
  obj_name_erpide_actbasepanel    = 'actBasePanel';
  obj_name_erpide_actbasestdlib   = 'actBaseStdLib';
  obj_name_erpide_actbasegv       = 'actBaseGlobalVariables';
  obj_name_erpide_actbaseexit     = 'actBaseExit';    
