{$DEFINE PEAKTOP:IDE/ERP/MAINMENU_LANG.INC}
const  //=================== PEAKTOP:IDE/ERP/MAINMENU_LANG.INC =================
  msg_erpide_mimainbase     = 'База';
  msg_erpide_actbasenew     = 'Создать'              ;msg_erpide_actbasenew_hint     = 'Создать базу данных';
  msg_erpide_actbaseopen    = 'Подключиться'         ;msg_erpide_actbaseopen_hint    = 'Подключиться к базе данных';
  msg_erpide_actbaseclose   = 'Отключиться'          ;msg_erpide_actbaseclose_hint   = 'Отключиться от базы данных';
  msg_erpide_actbaseatchs   = 'Подключения'          ;msg_erpide_actbaseatchs_hint   = 'Активные подключения к базе данных';
  msg_erpide_actbasefs      = 'Файловая система'     ;msg_erpide_actbasefs_hint      = 'Файловая система базы данных';
  msg_erpide_actbasegv      = 'Глобальные переменные';msg_erpide_actbasegv_hint      = 'Глобальные переменные';
  msg_erpide_actbaseconfig  = 'Кофигуратор'          ;msg_erpide_actbaseconfig_hint  = 'Кофигуратор базы данных';
  msg_erpide_actbasemenu    = 'Перезагрузить меню'   ;msg_erpide_actbasemenu_hint    = 'Перезагрузить Главное меню программы';
  msg_erpide_actbasebuffer  = 'Буфер обмена'         ;msg_erpide_actbasebuffer_hint  = 'Буфер обмена базы данных';
  msg_erpide_actbaserecent  = 'Последние действия'   ;msg_erpide_actbaserecent_hint  = 'Последние действия текущего пользователя';
  msg_erpide_actbasepanel   = 'Панель вызова'        ;msg_erpide_actbasepanel_hint   = 'Показать спрятать Панель вызова';
  msg_erpide_actbasestdlib  = 'Библиотека'           ;msg_erpide_actbasestdlib_hint  = 'Стандартная библиотека кода';
  msg_erpide_actbaseexit    = 'Выход'                ;msg_erpide_actbaseexit_hint    = 'Закрыть программу';
const  
  msg_erpide_error_accessdenied           = 'Отказно в доступе';
  msg_erpide_error_userhasnotright        = 'Текущий пользователь не имеет прав доступа.';
  msg_erpide_error_userhasnotrightsadmin  = 'Текущий пользователь не имеет административных прав доступа.';    
