{$DEFINE PEAKTOP:IDE/ERP/DBO/MENU/OBJECTEDITOR_NAMES.INC}
const //=========== PEAKTOP:IDE/ERP/DBO/MENU/OBJECTEDITOR_NAMES.INC ============
  obj_name_erp_objedtrmenu_caption          = 'dbeNAME';
  obj_name_erp_objedtrmenu_script           = 'dbeSCRIPT_NAME';
  obj_name_erp_objedtrmenu_shortcut         = 'dbeSHORTCUT';
  obj_name_erp_objedtrmenu_imageindex       = 'dbcbxIMAGE_INDEX';
  obj_name_erp_objedtrmenu_groupindex       = 'dbneGROUP_INDEX';
  obj_name_erp_objedtrmenu_tsaccss          = 'tsAccess';
  obj_name_erp_objedtrmenu_tslocal          = 'tsLocal';
  obj_name_erp_objedtrmenu_access           = 'Access';
  obj_name_erp_objedtrmenu_actaccss_inherit = 'actAccsInherit';
  obj_name_erp_objedtrmenu_actaccss_fill    = 'actAccsFill';
  obj_name_erp_objedtrmenu_actaccss_clear   = 'actAccsClear';      
