{$DEFINE PEAKTOP:IDE/ERP/DBO/MENU/OBJECTEDITOR_LANG.INC}
const  //============= PEAKTOP:IDE/ERP/DBO/MENU/OBJECTEDITOR_LANG.INC ==========
  msg_erp_objeditormenu_error001         = 'Нельзя удалить пункт меню, т.к. он унаследован от родительского типа документов.'+#13#10+
                                           'Откройте редактор меню для родительского типа документов и дулите этот пункт меню там.';
  msg_erp_objeditormenu_props            = 'свойства пункта меню';
  msg_erp_objeditormenu_caption          = 'Заголовок';
  msg_erp_objeditormenu_script           = 'Выполнить';
  msg_erp_objeditormenu_shortcut         = 'Команда';
  msg_erp_objeditormenu_imageindex       = 'Картинка';
  msg_erp_objeditormenu_groupindex       = 'Индекс';
  msg_erp_objeditormenu_menuaccss        = 'Доступ к пункту меню';
  msg_erp_objeditormenu_menulocal        = 'Локализация';
  msg_erp_objeditormenu_access           = 'Доступ';
  msg_erp_objeditormenu_enter_name       = 'Введите заголовок меню';
  msg_erp_objeditormenu_image_case       = 'Выбрать номер картинки';
  msg_erp_objeditormenu_file_case        = 'Выбрать внешний файл';
  msg_erp_objeditormenu_file_casedb      = 'Выбрать файл из базы данных';
  msg_erp_objeditormenu_opendialogfilter = 'Pascal Script (*.PS)|*.PS|Все файлы (*.*)|*.*';
  msg_erp_objeditormenu_dbg_role_img     = 'Роль|..';
  msg_erp_objeditormenu_dbg_role_id      = 'Роль|код';
  msg_erp_objeditormenu_dbg_role_name    = 'Роль|название';
  msg_erp_objeditormenu_dbg_role_accss   = 'Роль|доступ';
  msg_erp_actaccss_inherit = 'Наследовать'  ;msg_erp_actaccss_inherit_hint = 'Заполнить настройки доступа дочерних пунктов меню настройками доступа текущего пункта меню';
  msg_erp_actaccss_fill    = 'Доступ всем'  ;msg_erp_actaccss_fill_hint    = 'Дать доступ к текущему пункту меню всем ролям доступа';
  msg_erp_actaccss_clear   = 'Доступ никому';msg_erp_actaccss_clear_hint   = 'Лишить все роли права доступа к текущему пункту меню';    
