{$DEFINE PEAKTOP:IDE/MAINMENU_OBJNAMES.INC}
const //=================== PEAKTOP:IDE/MAINMENU_OBJNAMES.INC ==================
  obj_name_mimainwindow    = 'miMainWindow';
  obj_name_mimainhelp      = 'miMainHelp';
  obj_name_actwndlist      = 'actWindowList';
  obj_name_actwndcascade   = 'actWindowCascade';
  obj_name_actwndtilehor   = 'actWindowTileHorizontal';
  obj_name_actwndtilever   = 'actWindowTileVertical';
  obj_name_actwndnext      = 'actWindowNext';
  obj_name_actwndprev      = 'actWindowPervious';
  obj_name_actwndclose     = 'actWindowCloseActive';
  obj_name_actwndcloseall  = 'actWindowCloseAll';
  obj_name_actwndtaskbar   = 'actWindowTaskBar';
  obj_name_acthelpupdatelib= 'actHelpUpdateLibrary';
  obj_name_acthelpabout    = 'actHelpAbout';      
