{$DEFINE PEAKTOP:IDE/MAINMENU_LANG.INC}
const  //=================== PEAKTOP:IDE/MAINMENU_LANG.INC =====================
  msg_mimainwindow     = 'Окна';
  msg_mimainhelp       = '?';
  msg_actwndlist       = 'Открытые окна'      ;msg_actwndlist_hint       = 'Список открытых окон';
  msg_actwndcascade    = 'Каскадом'           ;msg_actwndcascade_hint    = 'Расположить окна каскадом';
  msg_actwndtilehor    = 'Горизонтально'      ;msg_actwndtilehor_hint    = 'Расположить окна равномерно горизонтально';
  msg_actwndtilever    = 'Вертикально'        ;msg_actwndtilever_hint    = 'Расположить окна равномерно вертикально';
  msg_actwndprev       = 'Следующее'          ;msg_actwndprev_hint       = 'Следующее окно';
  msg_actwndnext       = 'Предыдущее'         ;msg_actwndnext_hint       = 'Предыдущее окно';
  msg_actwndclose      = 'Закрыть активное'   ;msg_actwndclose_hint      = 'Закрыть активное окно';
  msg_actwndcloseall   = 'Закрыть все'        ;msg_actwndcloseall_hint   = 'Закрыть все окна программы';
  msg_actwndtaskbar    = 'Панель окон'        ;msg_actwndtaskbar_hint    = 'Показать или спрятать панель окон';
  msg_acthelpupdatelib = 'Обновить библиотеку';msg_acthelpupdatelib_hint = 'Обновить стандартную библиотеку кода';
  msg_acthelpabout     = 'О программе'        ;msg_acthelpabout_hint     = 'О программе';      
