{$DEFINE PEAKTOP:IDE/ERP/DBO/$COMMON/FORMERP_CONST.INC}
const //========== PEAKTOP:IDE/ERP/DBO/$COMMON/FORMERP_CONST.INC ===============
  TERPForm_DefaultToolBarBorderStyle = xbsNone;
  TERPForm_DefaultToolButtonWidth    = 24;  
  TERPForm_DefaultEditButtonWidth    = 96;
  TERPForm_DefaultToolSeparatorWidth =  8;               
  TERPForm_DefaultControlIndent      =  4;
  TERPForm_DefaultControlHeight      = 22;
  TERPForm_DefaultControlEditHeight  = 16; 
  TERPForm_DefaultControlWidthMul    = 1.800000;    
