{$DEFINE PEAKTOP:IDE/ERP/DBO/$COMMON/FORMERPEDTR_PAGEPARNT.INC}
  //============ PEAKTOP:IDE/ERP/DBO/$COMMON/FORMERPEDTR_PAGEPARNT.INC =========
  procedure TERPFormEdtr_PageParnt_Create(aOwner:TComponent; aMainPageControl:TxcPageControlEx; aMenuItemMain:TMenuItem; aDataSet:TxFBDataSet; aDataSource:TDataSource);
  {
  var
    lkAct      :TCustomAction;
    lkPCDetail :TxcPageControlEx;
    lkSplt     :TSplitter; 
    lkDBG      :TDBGridEh;
    lkDBGDetail:TDBGridEh;
    lkCol      :TColumnEh;
    lkDTSChild :TxFBDataSet; 
    lkDTSDetail:TxFBDataSet; 
  }
  begin
  end;
