{$DEFINE PEAKTOP:COM/GOOGLE/MAPS/CONST.INC}
const //================= PEAKTOP:COM/GOOGLE/MAPS/CONST.INC ====================
  google_maps_url_image                 = 'maps.google.com/maps/api/staticmap?';
  google_maps_url_image_param_zoom      = 'zoom';
  google_maps_url_image_param_size      = 'size';
  google_maps_url_image_param_type      = 'maptype';
  google_maps_url_image_param_type_map  = 'map';
  google_maps_url_image_param_type_hyb  = 'hybrid';
  google_maps_url_image_param_type_sat  = 'satellite';
  google_maps_url_image_param_format    = 'format';
  google_maps_url_image_param_formatpng = 'png';
  google_maps_url_image_param_formatgif = 'gif';
  google_maps_url_image_param_formatjpg = 'jpg';
  google_maps_url_image_param_sensor    = 'sensor';
  google_maps_url_image_param_center    = 'center';   
