{$DEFINE PEAKTOP:IDE/FIREBIRD/DIALOGS/$SETTINGS.INC}
const //============ PEAKTOP:IDE/FIREBIRD/DIALOGS/$SETTINGS.INC ================
  DefaultFirebirdDialogImageLogoLeft    = 'PEAKTOP:IMG/FIREBIRD/LOGO_002.BMP';
  DefaultFirebirdDialogImageLogoTop     = 'PEAKTOP:IMG/FIREBIRD/LOGO_004.BMP';
  DefaultFirebirdDialogImageLogoError   = 'PEAKTOP:IMG/FIREBIRD/LOGO_007.BMP';
  DefaultFirebirdDialogHeight           = 354;
  DefaultFirebirdDialogWidth            = 580;
  DefaultFirebirdDialogDBSettingsHeight = 354;
  DefaultFirebirdDialogErrorHeight      = 220;
  DefaultFirebirdDialogLabelWidth       = 96;
  DefaultFirebirdDialogButtonEtcWidth   = 120;
  DefaultFirebirdDialogLabelFontHeight  = 8;
  DefaultFirebirdDialogEditFontHeight   = 8;
  DefaultFirebirdDialogButtonFontHeight = 8;
