{$DEFINE PEAKTOP:IDE/FIREBIRD/DIALOGS/OBJNAMES.INC}
const //============== PEAKTOP:IDE/FIREBIRD/DIALOGS/OBJNAMES.INC ===============
  obj_name_fb_topbar           = 'TopBar';
  obj_name_fb_paneltop         = 'PanelTop';
  obj_name_fb_panelleft        = 'PanelLeft';
  obj_name_fb_panelright       = 'PanelRight';
  obj_name_fb_panelbottom      = 'PanelBottom';
  obj_name_fb_panelclinet      = 'PanelClient';
  obj_name_fb_imglogotop       = 'ImgLogo';
  obj_name_fb_imglogoleft      = 'ImgLogoLeft';
  obj_name_fb_imgbackgrndright = 'ImgBackgrndRight';
  
