{$DEFINE PEAKTOP:IDE/DEVELOPMENT/EDITOR/OBJNAMES.INC}
const //============== PEAKTOP:IDE/DEVELOPMENT/EDITOR/OBJNAMES.INC ============= 
  ERP_FILENAME_BMP_ACTCLOSE       = 'PEAKTOP:IMG/ICONS/DIALOGS_CLOSE_0032X0032.BMP'; 
  ERP_FILENAME_BMP_ACTAPPLY       = 'PEAKTOP:IMG/ICONS/DIALOGS_APPLY_0032X0032.BMP'; 
  ERP_FILENAME_BMP_ACTHELP        = 'PEAKTOP:IMG/ICONS/DIALOGS_CONFIRMATION_0032X0032.BMP'; 
  ERP_FILENAME_BMP_ACTSOURCECODE  = 'PEAKTOP:IMG/ICONS/PASCALSCRIPT0032X0032.BMP'; 
  editor_obj_name_toolbarmain         = 'Editor_ToolBarMain';
  editor_obj_name_page_control        = 'Editor_PageControl';
  editor_obj_name_codetree            = 'Editor_CodeTree';
  editor_obj_name_codetree_splitter   = 'Editor_CodeTree_Splitter';
  editor_obj_name_treeview_code       = 'Editor_TreeView_Code';
  editor_obj_name_listview_messages   = 'Editor_ListView_Messages';
  editor_obj_name_synedit_messages    = 'Editor_SynEdit_Messages';
  editor_obj_name_synedit_preprocess  = 'Editor_SynEdit_Preprocess';  
