{$DEFINE PEAKTOP:IDE/ERP/DBO/OPER/ENT/PS_COUNTRIES_LANG.INC}
  //=========== PEAKTOP:IDE/ERP/DBO/OPER/ENT/PS_COUNTRIES_LANG.INC =============
const
  msg_erp_entps_settings_countries      = 'Настройки курсов оценки и процентов за пользование';
  msg_erp_entps_settings                = 'Настройки курса';
  
  msg_erp_entps_settings_courses        = 'Курсы оценки';
  msg_erp_entps_settings_metals_course  = 'Оценка по пробам'; 
  msg_erp_entps_settings_metals         = 'Драгоценные металлы (цена за 1 грамм)';
  msg_erp_entps_settings_metals_probe   = 'ПРОБА';
  msg_erp_entps_settings_metals_au      = 'ЗОЛОТО';
  msg_erp_entps_settings_metals_ag      = 'СЕРЕБРО';
  msg_erp_entps_settings_metals_pt      = 'ПЛАТИНА';
  msg_erp_entps_settings_metals_pd      = 'ПАЛЛАДИЙ';
  msg_erp_entps_settings_pc_grids       = 'Сетки процентов';
  msg_erp_entps_settings_grid_summin    = 'Минимальная сумма кредита|UAH';
  msg_erp_entps_settings_grid_daysfrom  = 'Количество дней кредита|дней';
  msg_erp_entps_settings_grid_dayspc    = 'Процент в день за пользование кредитом|Основной';
  msg_erp_entps_settings_grid_dayspcpen = 'Процент в день за пользование кредитом|За просрочку';
  msg_erp_entps_settings_grid_coment    = 'Примечание';
  msg_erp_entps_settings_grid_recid     = 'Код записи';    
