{$DEFINE PEAKTOP:IDE/ERP/DATABASE/DLG_LANG.INC}
const //================ PEAKTOP:IDE/ERP/DATABASE/DLG_LANG.INC =================
  msg_erpdatabase                    = 'База данных';
  msg_erpdatabasedlg_select          = 'Выберите базу данных';
  msg_erpdatabasedlg_loadtype        = 'Тип загрузки';
  msg_erpdatabasedlg_loadtype_local  = 'Локально';
  msg_erpdatabasedlg_loadtype_remote = 'Удаленно';
  msg_erpdatabasedlg_filial_name     = 'Филиал';    
