{$DEFINE PEAKTOP:COM/MICROSOFT/OFFICE/EXCEL/CONST.INC}
const //============ PEAKTOP:COM/MICROSOFT/OFFICE/EXCEL/CONST.INC ==============
  // text alignment const
  MSEXCEL_xlBottom           = $FFFFEFF5;
  MSEXCEL_xlLeft             = $FFFFEFDD;
  MSEXCEL_xlRight            = $FFFFEFC8;
  MSEXCEL_xlTop              = $FFFFEFC0;
  MSEXCEL_xlJustify          = $FFFFEFDE;
  MSEXCEL_xlCenter           = $FFFFEFF4;
  // orientation
  MSEXCEL_xlDownward         = -4170; 
  MSEXCEL_xlHorizontal       = -4128; 
  MSEXCEL_xlUpward           = -4171; 
  MSEXCEL_xlVertical         = -4166;
  // Page orientation
  MSEXCEL_xlLandscape        = 2; 
  MSEXCEL_xlPortrait         = 1;
  // border Weight  
  MSEXCEL_xlHairline         = $00000001;
  MSEXCEL_xlMedium           = $FFFFEFD6;
  MSEXCEL_xlThick            = $00000004;
  MSEXCEL_xlThin             = $00000002;
  // line styles const
  MSEXCEL_xlContinuous       = $00000001;
  MSEXCEL_xlDash             = $FFFFEFED;
  MSEXCEL_xlDashDot          = $00000004;
  MSEXCEL_xlDashDotDot       = $00000005;
  MSEXCEL_xlDot              = $FFFFEFEA;
  MSEXCEL_xlDouble           = $FFFFEFE9;
  MSEXCEL_xlSlantDashDot     = $0000000D;
  MSEXCEL_xlLineStyleNone    = $FFFFEFD2;
  // border indicies
  MSEXCEL_xlInsideHorizontal = $0000000C;
  MSEXCEL_xlInsideVertical   = $0000000B;
  MSEXCEL_xlDiagonalDown     = $00000005;
  MSEXCEL_xlDiagonalUp       = $00000006;
  MSEXCEL_xlEdgeBottom       = $00000009;
  MSEXCEL_xlEdgeLeft         = $00000007;
  MSEXCEL_xlEdgeRight        = $0000000A;
  MSEXCEL_xlEdgeTop          = $00000008;
