{$DEFINE PEAKTOP:IDE/REGEDIT/MAINMENU/LANG.INC}
const  //=================== PEAKTOP:IDE/FIREBIRD/MAINMENU/LANG.INC ============
  msg_regide_mimainwindow   = 'Окна';
  msg_regide_mimainhelp     = '?';
  msg_regide_actwndlist     = 'Открытые окна'   ;msg_regide_actwndlist_hint     = 'Список открытых окон';
  msg_regide_actwndcascade  = 'Каскадом'        ;msg_regide_actwndcascade_hint  = 'Расположить окна каскадом';
  msg_regide_actwndtilehor  = 'Горизонтально'   ;msg_regide_actwndtilehor_hint  = 'Расположить окна равномерно горизонтально';
  msg_regide_actwndtilever  = 'Вертикально'     ;msg_regide_actwndtilever_hint  = 'Расположить окна равномерно вертикально';
  msg_regide_actwndprev     = 'Следующее'       ;msg_regide_actwndprev_hint     = 'Следующее окно';
  msg_regide_actwndnext     = 'Предыдущее'      ;msg_regide_actwndnext_hint     = 'Предыдущее окно';
  msg_regide_actwndclose    = 'Закрыть активное';msg_regide_actwndclose_hint    = 'Закрыть активное окно';
  msg_regide_actwndcloseall = 'Закрыть все'     ;msg_regide_actwndcloseall_hint = 'Закрыть все окна программы';
  msg_regide_actwndtaskbar  = 'Панель окон'     ;msg_regide_actwndtaskbar_hint  = 'Показать или спрятать панель окон';
  msg_regide_acthelpabout   = 'О программе'     ;msg_regide_acthelpabout_hint   = 'О программе';
