{$DEFINE PEAKTOP:IDE/REGEDIT/MAINMENU/OBJNAMES.INC}
const //=================== PEAKTOP:IDE/FIREBIRD/MAINMENU/OBJNAMES.INC =========
  obj_name_regide_mimainbase      = 'miMainBase';
  obj_name_regide_mimainwindow    = 'miMainWindow';
  obj_name_regide_mimainhelp      = 'miMainHelp';
  obj_name_regide_actwndlist      = 'actWindowList';
  obj_name_regide_actwndcascade   = 'actWindowCascade';
  obj_name_regide_actwndtilehor   = 'actWindowTileHorizontal';
  obj_name_regide_actwndtilever   = 'actWindowTileVertical';
  obj_name_regide_actwndnext      = 'actWindowNext';
  obj_name_regide_actwndprev      = 'actWindowPervious';
  obj_name_regide_actwndclose     = 'actWindowCloseActive';
  obj_name_regide_actwndcloseall  = 'actWindowCloseAll';
  obj_name_regide_actwndtaskbar   = 'actWindowTaskBar';
  obj_name_regide_acthelpabout    = 'actHelpAbout';    
