{$DEFINE PEAKTOP:IDE/ERP/DBO/OPER/FILESYSTEM_LANG.INC}
const //================== PEAKTOP:IDE/ERP/DBO/FS/LANG.INC =====================
  msg_erp_dbfs_caption                = 'Файловая система базы данных';
  msg_erp_dbfs_enternewfoldername     = 'Введите имя каталога';
  msg_erp_dbfs_enternewfilename       = 'Введите имя файла';
  msg_erp_dbfs_enternewfileext        = 'Введите расширение файла';
  msg_erp_dbfs_filesendtofilialsucces = 'На филиал оправлено файлов: ';  
  msg_erp_dbfs_filesendtofilialerror  = 'Ошибка при отправке файла(ов):';
  msg_erp_dbfs_connections            = 'Подключения';    
