{$DEFINE PEAKTOP:IDE/ERP/DBO/DBGRID/PRINT/LANG.INC}
const //========= PEAKTOP:IDE/ERP/DBO/DBGRID/PRINT/LANG.INC ====================
  msg_print_dialog_error_sql001= 'Невозможно выполнить выбор шаблона печати.'+#13#10+'Отсутствует файл конфигурации.'+#13#10;
  msg_print_dialog_doc_caption = 'Выберите шаблон печати';
  msg_print_dialog_report_name = 'Название шаблона печати';
  msg_print_dialog_report_path = 'имя файла шаблона печати';
  msg_print_dialog_doc_name    = 'Тип документов';
